#!/bin/bash
flutter build apk --build-name --build-number
#mv build/app/outputs/flutter-apk/app-release.apk

scp -P 10000 build/app/outputs/flutter-apk/app-release.apk \
    gilmario@gilmariosoftware.com.br:/opt/volumes/site/downloads