#!/bin/bash
# LER AS INFORMACOES

echo "build versao v1.0.0 numero $1"

flutter build apk --build-name v1.0.0 --build-number $1
#mv build/app/outputs/flutter-apk/app-release.apk

echo "publicando atualizacao"

scp -P 10000 build/app/outputs/flutter-apk/app-release.apk \
    gilmario@gilmariosoftware.com.br:/opt/volumes/site/downloads